import test from 'node:test';
import assert from 'node:assert/strict';
import {GestureRecognizer,extractFeatures} from '../dist/recognizer.js';
import {Course} from '../dist/course.js';
import {HandCommands} from '../dist/commands.js';

const finger=(extended)=>({extended,folded:!extended});
const feature=(type='ily',overrides={})=>({fingers:(type==='ily'?[true,false,false,true]:type==='no'?[true,true,false,false]:[false,false,false,false]).map(finger),thumbOut:type==='ily',facingCamera:true,pitch:0,screenScale:.2,cropped:false,closeGap:1,pairTogether:true,indexUpright:true,...overrides});
const feed=(engine,f,start,end,target)=>{let r;for(let t=start;t<=end;t+=50)r=engine.updateFeatures(f,t,target);return r;};

test('ILY requires a full second of valid observations, not a single matching frame',()=>{const r=new GestureRecognizer();assert.equal(r.updateFeatures(feature(),0,'ily').success,false);assert.equal(feed(r,feature(),50,950,'ily').success,false);assert.equal(r.updateFeatures(feature(),1000,'ily').success,true);});
test('A cropped or missing hand cannot complete an in-progress hold',()=>{const r=new GestureRecognizer();feed(r,feature(),0,950,'ily');assert.equal(r.updateFeatures(null,1000,'ily').kind,'tracking');assert.equal(r.updateFeatures(feature(),1100,'ily').success,false);assert.equal(r.updateFeatures(feature('ily',{cropped:true}),1150,'ily').success,false);});
test('A long frame gap resets temporal progress even without a null frame',()=>{const r=new GestureRecognizer();feed(r,feature(),0,900,'ily');const out=r.updateFeatures(feature(),2200,'ily');assert.equal(out.success,false);assert.equal(out.progress,0);});
test('One noisy frame every 600 ms pauses ILY progress without preventing completion',()=>{const r=new GestureRecognizer();let completed=false;for(let t=0;t<=2400;t+=100){const f=feature();if(t%600===500)f.fingers[1]=finger(true);const out=r.updateFeatures(f,t,'ily');if(t%600===500)assert.equal(out.success,false);completed||=out.success;}assert.ok(completed);});
test('A slow 3 FPS camera can complete ILY',()=>{const r=new GestureRecognizer();let out;for(let t=0;t<=1665;t+=333)out=r.updateFeatures(feature(),t,'ily');assert.ok(out.success);});
test('Sustained wrong fingers reset a partial hold instead of earning success',()=>{const r=new GestureRecognizer();feed(r,feature(),0,700,'ily');const f=feature();f.fingers[3]=finger(false);const out=feed(r,f,750,1300,'ily');assert.equal(out.progress,0);assert.equal(out.success,false);assert.equal(r.updateFeatures(feature(),1400,'ily').progress,0);});
test('Wrong ILY finger receives an actionable correction and affected joint group',()=>{const r=new GestureRecognizer();const f=feature();f.fingers[3]=finger(false);const out=r.updateFeatures(f,0,'ily');assert.match(out.title,/мизинец/);assert.deepEqual(out.badFingers,[4]);assert.equal(out.success,false);});
test('A still fist and tiny tracking jitter never count as YES',()=>{const r=new GestureRecognizer();for(let t=0;t<6000;t+=50){const out=r.updateFeatures(feature('yes',{pitch:Math.sin(t)*.06}),t,'yes');assert.equal(out.success,false);}});
test('YES needs a wrist pitch change AND a return',()=>{const r=new GestureRecognizer();feed(r,feature('yes'),0,250,'yes');assert.equal(feed(r,feature('yes',{pitch:.65}),300,650,'yes').success,false);assert.equal(feed(r,feature('yes'),700,1000,'yes').success,true);});
test('NO cannot be recognized from a closed pinch alone',()=>{const r=new GestureRecognizer();assert.equal(feed(r,feature('no',{closeGap:.1}),0,2000,'no').success,false);});
test('NO recognizes ordered opening then closing, not an inverted sequence',()=>{const r=new GestureRecognizer();feed(r,feature('no',{closeGap:.1}),0,500,'no');assert.equal(feed(r,feature('no'),550,800,'no').success,false);assert.equal(r.updateFeatures(feature('no',{closeGap:.12}),1000,'no').success,true);});
test('NO opened more than 3.5 seconds ago is not a live gesture',()=>{const r=new GestureRecognizer();feed(r,feature('no'),0,300,'no');for(let t=350;t<=4000;t+=50)r.updateFeatures(feature('no',{closeGap:.5}),t,'no');assert.equal(r.updateFeatures(feature('no',{closeGap:.12}),4050,'no').success,false);});
test('Changing the lesson resets any partial gesture',()=>{const r=new GestureRecognizer();feed(r,feature(),0,950,'ily');r.updateFeatures(feature('yes'),1000,'yes');assert.equal(r.updateFeatures(feature(),1100,'ily').success,false);});
test('Course requires all three signs and the phrase in the correct order',()=>{const c=new Course();c.begin(0);assert.equal(c.accept('no',1000),false);assert.equal(c.target,'ily');for(const [i,s] of ['ily','yes','no'].entries())assert.equal(c.accept(s,1000+i*1000),true);assert.equal(c.stage,'phrase');assert.equal(c.accept('ily',3500),false);c.accept('yes',4000);c.accept('ily',5000);assert.equal(c.stage,'done');assert.equal(c.summary().checks,5);assert.equal(c.summary().score,100);assert.equal(c.accept('yes',6000),false);});
test('Score is based on actual completion, excludes paused time, and resets',()=>{const c=new Course();assert.equal(c.summary().score,0);c.begin(1000);c.recordCorrection();c.pause(2000);c.resume(5000);['ily','yes','no','yes','ily'].forEach((s,i)=>c.accept(s,6000+i*1000));assert.equal(c.summary().score,97);assert.equal(c.summary().seconds,6);c.restart();assert.equal(c.summary().score,0);assert.equal(c.learned.size,0);});

// A simple synthetic 21-joint skeleton tests geometry, not the neural detector.
function openHand(){return [[.5,.8],[.4,.68],[.32,.61],[.25,.55],[.18,.49],[.42,.55],[.42,.39],[.42,.28],[.42,.19],[.5,.52],[.5,.34],[.5,.22],[.5,.12],[.58,.54],[.58,.39],[.58,.29],[.58,.2],[.65,.59],[.65,.47],[.65,.39],[.65,.3]].map(([x,y])=>({x,y,z:0}));}
test('Geometry recognizes extended fingers and is invariant under translation/scale',()=>{const s=openHand(),a=extractFeatures(s,null,1,'Right');assert.ok(a.fingers.every(f=>f.extended));assert.ok(a.openPalm);const p=s.map(v=>({x:.12+v.x*.8,y:.04+v.y*.8,z:0})),b=extractFeatures(p,null,1,'Right');assert.deepEqual(b.fingers.map(f=>f.extended),a.fingers.map(f=>f.extended));assert.equal(b.thumbOut,a.thumbOut);});
test('Mirroring with the opposite handedness preserves palm orientation',()=>{const p=openHand(),a=extractFeatures(p,null,1,'Right'),b=extractFeatures(p.map(v=>({...v,x:1-v.x})),null,1,'Left');assert.equal(a.facingCamera,b.facingCamera);assert.equal(a.openPalm,b.openPalm);});
test('Invalid or zero-length landmark sets never produce valid features',()=>{assert.equal(extractFeatures([]),null);assert.equal(extractFeatures(Array.from({length:21},()=>({x:0,y:0,z:0}))),null);const p=openHand();p[4].x=NaN;assert.equal(extractFeatures(p),null);});
test('Two-palm pause triggers once per hold and rearms only after release',()=>{const c=new HandCommands(),p=feature('ily',{openPalm:true});c.update([p,p],0);assert.equal(c.update([p,p],1100).action,null);assert.equal(c.update([p,p],1200).action,'pause');assert.equal(c.update([p,p],1400).action,null);c.update([],1600);c.update([],2100);c.update([p,p],2200);assert.equal(c.update([p,p],3500).action,'pause');});
test('Two fists open the reference while a single ASL fist does not trigger UI',()=>{const c=new HandCommands(),p=feature('yes');c.update([p],0);assert.equal(c.update([p],1500).action,null);c.update([p,p],2000);assert.equal(c.update([p,p],3250).action,'example');});
